title: OVGTSL Conference 2024
preposition: ''
description: >-
  A Century of OVGTSL: Technical Services in the Past, Present, and Future
url: "https://2024.ovgtslibrarians.org"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


# ------------------------------------------------------
# CONFERENCE
# ------------------------------------------------------
conference:
  lang: en  # Language
  show_errors: False  # Show theme errors

  # Navigation bar
  navigation:
    links:
      - name: Proposals
        relative_url: /proposals/
        #disabled: true
        hide: true
      - name: Attend
        menu:
          - name: Registration
            absolute_url: https://www.eventbrite.com/e/ovgtsl-conference-2024-registration-795359771487
            disabled: false
          - name: Hotel
            absolute_url: https://www.hilton.com/en/attend-my-event/ohiovalleygrptsl-90w/
            disabled: false
      - name: Program
        relative_url: /program/#thursday
        disabled: false
        hide: false
      - name: Scholarships
        relative_url: /scholarships/
        disabled: false
        hide: false

  # Main landing page
  main:
    img: 'oclc_conference_center.jpg'
    links:
      - name: Submit a Proposal
        relative_url: /proposals/
        disabled: True
        hide: true
      - name: Scholarship Application
        relative_url: /scholarships/
        disabled: False
        hide: false
      - name: Reserve a Room
        absolute_url: https://www.hilton.com/en/attend-my-event/ohiovalleygrptsl-90w/
        disabled: False
        hide: false
      - name: Register for Conference
        absolute_url: https://www.eventbrite.com/e/ovgtsl-conference-2024-registration-795359771487
        disabled: False
        hide: false

  # Information boxes
  info_bars:
  #  - title: SUBMIT A PROPOSAL!
  #    color: primary
  #    main_only: true
  #    text: |
  #      Proposals accepted through February 29, 2024 - see the [proposals](/proposals/) page for details.
    - title: NOW ACCEPTING STUDENT SCHOLARSHIP APPLICATIONS!
      color: primary
      main_only: true
      text: |
        Applications accepted through March 18, 2024 - see the [scholarships](/scholarships/) page for details.

  link_preview:
    disable: false

  talks:
    # Talk categories
    main_categories:
      - name: General
        color: secondary
      - name: Keynote
        color: warning
      - name: Room A
        color: primary
      - name: Room B
        color: info
      - name: Room C
        color: success

  speakers:
    show_firstname: true

  location:
    url: '/location'
    map: true

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true
    show_categories: false
