title: OVGTSL Conference 2024
preposition: ''
description: >-
  A Century of OVGTSL: Technical Services in the Past, Present, and Future
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://example.com" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: False

  # Navigation bar
  navigation:
    links:
      - name: Proposals
        relative_url: /proposals/

  # Main landing page
  main:
    img: 'oclc_conference_center.jpg'
    links:
      - name: Submit a Proposal
        relative_url: /proposals/
        disabled: False

  # Information boxes
  info_bars:
    - title: SUBMIT A PROPOSAL!
      color: primary
      main_only: true
      text: |
        Proposals accepted until February 9, 2024 - see the [proposals](/proposals/) page for details.

  link_preview:
    disable: false

  speakers:
    show_firstname: true

  location:
    url: '/location'
    map: true

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true
